[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4da3ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#e6e6e6"
